---
base_url: 'http://localhost:5000'
session:
    secret: '123'
mailer:
    subject_prefix: '[Toks]'
    headers:
        - 'From'
        - 'foo@bar.com'
    transport:
        name: 'test'
        path: '/tmp/mailer.log'
