---
base_url: 'http://localhost:5000'
pagers:
    threads: 5
    subscriptions: 5
    notifications: 5
limits:
    threads:
        60: 2
        3600: 5
        86400: 10
    replies:
        60: 2
        3600: 5
        86400: 20
session:
    secret: '123'
database:
    dsn: 'dbi:SQLite:db.db'
    attrs:
        RaiseError: 1
        sqlite_unicode: 1
i18n:
    default_language: 'ru'
    languages:
        - 'ru'
mailer:
    subject_prefix: '[Toks]'
    headers:
        - 'From'
        - 'foo@bar.com'
    transport:
        name: 'test'
        path: '/tmp/mailer.log'
