---
base_url: 'http://localhost:5000'
session:
    secret: '123'
mailer:
    subject_prefix: '[Threads]'
    headers:
        - 'From'
        - 'foo@bar.com'
    transport:
        name: 'test'
        path: '/tmp/mailer.log'
i18n:
    default_language: 'en'
    languages:
        - 'en'
